"""Deterministic plain-text rendering of the A6 nightly review alert email.
Pure function — no I/O, no model. Only sent when there is something to act
on (trim/exit/stale recommendations); quiet nights journal only."""
from __future__ import annotations

RULE = "-" * 62


def subject_line(run_date: str, recos: list[dict]) -> str:
    n = len(recos)
    tickers = ",".join(sorted({r["ticker"] for r in recos})[:4])
    return (f"A6 position review {run_date} — {n} recommendation"
            f"{'s' if n != 1 else ''} ({tickers})")


def render_review_alert(run_date: str, recos: list[dict], holds: list[dict],
                        stats: dict) -> str:
    L: list[str] = []
    L.append(f"NIGHTLY POSITION REVIEW — {run_date}")
    L.append(RULE)
    L.append("ACTION RECOMMENDED (review before tomorrow's open; nothing "
             "has been executed)")
    for r in recos:
        rp = r.get("r_progress")
        L.append(f"  {r['action']:<10} {r['ticker']} "
                 f"[{r['horizon']}, {r.get('sessions_held', '?')} sessions, "
                 f"R {rp if rp is not None else '?'}]")
        L.append(f"      {r['rationale'][:150]}")
    L.append(RULE)
    if holds:
        L.append(f"HOLDING ({len(holds)})")
        for h in holds:
            rp = h.get("r_progress")
            L.append(f"  {h['ticker']} [{h['horizon']}, "
                     f"R {rp if rp is not None else '?'}] — "
                     f"{h['rationale'][:100]}")
        L.append(RULE)
    L.append(f"Reviewed {stats['reviewed']} open position"
             f"{'s' if stats['reviewed'] != 1 else ''}; "
             f"{stats['stale_flagged']} stale-flagged by the code rule; "
             f"slot: {stats['slot']}.")
    L.append("Generated by A6 (recommendation-only; auto-apply is OFF). "
             "Stops and exits remain governed by C4's code layers and A12.")
    return "\n".join(L)
