"""Deterministic plain-text rendering of the A5 thesis digest email.
Pure function — no I/O, no model."""
from __future__ import annotations

RULE = "-" * 62


def subject_line(run_date: str, stats: dict) -> str:
    n_new = stats["new_theses"]
    n_ev = stats["evidence_attached"]
    if n_new == 0 and n_ev == 0:
        return f"Thesis digest {run_date} — no store changes"
    parts = []
    if n_new:
        parts.append(f"{n_new} new thes{'es' if n_new != 1 else 'is'}")
    if n_ev:
        parts.append(f"{n_ev} evidence item{'s' if n_ev != 1 else ''}")
    return f"Thesis digest {run_date} — " + ", ".join(parts)


def render_digest(run_date: str, summary: str, new_theses: list[dict],
                  evidence: list[dict], status_changes: list[dict],
                  expired: list[dict], stats: dict, slot_name: str) -> str:
    L: list[str] = []
    L.append(f"THESIS STORE DIGEST — {run_date}"
             f"{'  (Sunday deep pass)' if stats.get('deep') else ''}")
    L.append(RULE)
    L.append(summary)
    L.append(RULE)

    L.append(f"NEW THESES ({len(new_theses)})")
    if not new_theses:
        L.append("  None.")
    for t in new_theses:
        tickers = ",".join(b["ticker"] for b in t.get("beneficiaries", []))
        L.append(f"  {t['thesis_id']} [{t['direction']}, "
                 f"conf {t['confidence']:.2f}] {t['title'][:70]}")
        L.append(f"      beneficiaries: {tickers or '-'}")
    L.append(RULE)

    L.append(f"EVIDENCE ATTACHED ({len(evidence)})")
    if not evidence:
        L.append("  None.")
    for e in evidence[:10]:
        L.append(f"  {e['thesis_id']} [{e['polarity']}] "
                 f"{(e.get('headline') or e['item_id'])[:70]}")
    if len(evidence) > 10:
        L.append(f"  ... and {len(evidence) - 10} more")
    L.append(RULE)

    if status_changes or expired:
        L.append("STATUS CHANGES")
        for s in status_changes:
            L.append(f"  {s['thesis_id']} -> {s['status']} — "
                     f"{(s.get('note') or '')[:80]}")
        for x in expired:
            L.append(f"  {x['thesis_id']} -> EXPIRED (staleness rule) — "
                     f"{x['title'][:60]}")
        L.append(RULE)

    L.append(f"Store: {stats['active_after']} active theses. Lane: "
             f"{stats['processed']} items processed, {stats['ignored']} "
             f"ignored, {stats['expired_bulk']} stale bulk-expired, "
             f"{stats['left_queued']} left queued.")
    L.append("Generated by A5. Store writes by code from grammar-constrained "
             "model output; staleness expiry is deterministic.")
    return "\n".join(L)
