"""Deterministic plain-text rendering of the pre-market briefing email.
Pure function — no I/O, no model."""
from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo

CT = ZoneInfo("America/Chicago")
RULE = "-" * 62


def _t(iso: str) -> str:
    return datetime.fromisoformat(iso).astimezone(CT).strftime("%H:%M CT")


def subject_line(session_date: str, stats: dict) -> str:
    n = stats["open_candidates"]
    if n == 0:
        return f"Pre-market {session_date} — quiet night, no open candidates"
    return (f"Pre-market {session_date} — {n} open candidate"
            f"{'s' if n != 1 else ''} queued for {_t(stats['entry_ts'])}")


def render_briefing(session_date: str, summary: str, open_forwarded: list,
                    routed_guard: list, routed_thesis: list, stats: dict,
                    slot_name: str) -> str:
    L: list[str] = []
    L.append(f"PRE-MARKET ACTION SHEET — {session_date}")
    L.append(RULE)
    L.append(summary)
    if slot_name == "fallback":
        L.append("(model offline — deterministic priority ranking below)")
    L.append(RULE)

    L.append(f"OPEN CANDIDATES (analyst evaluates at {_t(stats['entry_ts'])}, "
             "open-handoff gate applies)")
    if not open_forwarded:
        L.append("  None.")
    for c in open_forwarded:
        L.append(f"  #{c['rank']} {','.join(c['tickers'])} — "
                 f"{(c['headline'] or '?')[:80]}")
        L.append(f"      {c['rationale'][:110]}")
    L.append(RULE)

    L.append("POSITION-TOUCHING (routed to A12 guard)")
    if not routed_guard:
        L.append("  None.")
    for g in routed_guard:
        L.append(f"  {','.join(g.get('tickers') or ['?'])} — "
                 f"{(g.get('headline') or '?')[:80]}")
    L.append(RULE)

    L.append(f"THESIS LANE ({len(routed_thesis)} item"
             f"{'s' if len(routed_thesis) != 1 else ''} for the long-horizon "
             "store)")
    for t in routed_thesis[:8]:
        L.append(f"  {(t.get('headline') or '?')[:86]}")
    if len(routed_thesis) > 8:
        L.append(f"  ... and {len(routed_thesis) - 8} more")
    L.append(RULE)

    L.append(f"Overnight queue: {stats['fresh']} fresh processed, "
             f"{stats['ignored']} ignored, {stats['expired_bulk']} stale "
             "bulk-expired.")
    L.append("Generated by A4. Ranking by model; all routing and gating by "
             "code — the open-handoff confirmation gate is unchanged.")
    return "\n".join(L)
